name: NewTest
main: CHL\NewTest\NewTest
api: 3.19.2
version: 0.0.2
author: XnoxyCHL
commands:
        coba:
            description: Percobaan
            usage: /coba
permissions:
        coba.command:
            default: true